global.spesialprem = 'khusus user premium!'
global.spesialown = 'khusus admin & owner dika id!'
global.notext = 'sertakan teks'
global.noingroup = 'fitur tersebut akan terbuka jika anda berada dalam grup!'
global.nobotadmin = 'fitur akan terbuka jika bot adalah admin!'
global.usernoadmin = 'fitur akan terbuka jika anda adalah admin!'